require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/componentes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Componente. As you add validations to Componente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Componente.create! valid_attributes
      get componentes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      componente = Componente.create! valid_attributes
      get componente_url(componente)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_componente_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      componente = Componente.create! valid_attributes
      get edit_componente_url(componente)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Componente" do
        expect {
          post componentes_url, params: { componente: valid_attributes }
        }.to change(Componente, :count).by(1)
      end

      it "redirects to the created componente" do
        post componentes_url, params: { componente: valid_attributes }
        expect(response).to redirect_to(componente_url(Componente.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Componente" do
        expect {
          post componentes_url, params: { componente: invalid_attributes }
        }.to change(Componente, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post componentes_url, params: { componente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested componente" do
        componente = Componente.create! valid_attributes
        patch componente_url(componente), params: { componente: new_attributes }
        componente.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the componente" do
        componente = Componente.create! valid_attributes
        patch componente_url(componente), params: { componente: new_attributes }
        componente.reload
        expect(response).to redirect_to(componente_url(componente))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        componente = Componente.create! valid_attributes
        patch componente_url(componente), params: { componente: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested componente" do
      componente = Componente.create! valid_attributes
      expect {
        delete componente_url(componente)
      }.to change(Componente, :count).by(-1)
    end

    it "redirects to the componentes list" do
      componente = Componente.create! valid_attributes
      delete componente_url(componente)
      expect(response).to redirect_to(componentes_url)
    end
  end
end
