require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/opciones", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Opcion. As you add validations to Opcion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Opcion.create! valid_attributes
      get opciones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      opcion = Opcion.create! valid_attributes
      get opcion_url(opcion)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_opcion_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      opcion = Opcion.create! valid_attributes
      get edit_opcion_url(opcion)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Opcion" do
        expect {
          post opciones_url, params: { opcion: valid_attributes }
        }.to change(Opcion, :count).by(1)
      end

      it "redirects to the created opcion" do
        post opciones_url, params: { opcion: valid_attributes }
        expect(response).to redirect_to(opcion_url(Opcion.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Opcion" do
        expect {
          post opciones_url, params: { opcion: invalid_attributes }
        }.to change(Opcion, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post opciones_url, params: { opcion: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested opcion" do
        opcion = Opcion.create! valid_attributes
        patch opcion_url(opcion), params: { opcion: new_attributes }
        opcion.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the opcion" do
        opcion = Opcion.create! valid_attributes
        patch opcion_url(opcion), params: { opcion: new_attributes }
        opcion.reload
        expect(response).to redirect_to(opcion_url(opcion))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        opcion = Opcion.create! valid_attributes
        patch opcion_url(opcion), params: { opcion: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested opcion" do
      opcion = Opcion.create! valid_attributes
      expect {
        delete opcion_url(opcion)
      }.to change(Opcion, :count).by(-1)
    end

    it "redirects to the opciones list" do
      opcion = Opcion.create! valid_attributes
      delete opcion_url(opcion)
      expect(response).to redirect_to(opciones_url)
    end
  end
end
