require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/opcion_cas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OpcionCa. As you add validations to OpcionCa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OpcionCa.create! valid_attributes
      get opcion_cas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      opcion_ca = OpcionCa.create! valid_attributes
      get opcion_ca_url(opcion_ca)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_opcion_ca_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      opcion_ca = OpcionCa.create! valid_attributes
      get edit_opcion_ca_url(opcion_ca)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OpcionCa" do
        expect {
          post opcion_cas_url, params: { opcion_ca: valid_attributes }
        }.to change(OpcionCa, :count).by(1)
      end

      it "redirects to the created opcion_ca" do
        post opcion_cas_url, params: { opcion_ca: valid_attributes }
        expect(response).to redirect_to(opcion_ca_url(OpcionCa.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OpcionCa" do
        expect {
          post opcion_cas_url, params: { opcion_ca: invalid_attributes }
        }.to change(OpcionCa, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post opcion_cas_url, params: { opcion_ca: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested opcion_ca" do
        opcion_ca = OpcionCa.create! valid_attributes
        patch opcion_ca_url(opcion_ca), params: { opcion_ca: new_attributes }
        opcion_ca.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the opcion_ca" do
        opcion_ca = OpcionCa.create! valid_attributes
        patch opcion_ca_url(opcion_ca), params: { opcion_ca: new_attributes }
        opcion_ca.reload
        expect(response).to redirect_to(opcion_ca_url(opcion_ca))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        opcion_ca = OpcionCa.create! valid_attributes
        patch opcion_ca_url(opcion_ca), params: { opcion_ca: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested opcion_ca" do
      opcion_ca = OpcionCa.create! valid_attributes
      expect {
        delete opcion_ca_url(opcion_ca)
      }.to change(OpcionCa, :count).by(-1)
    end

    it "redirects to the opcion_cas list" do
      opcion_ca = OpcionCa.create! valid_attributes
      delete opcion_ca_url(opcion_ca)
      expect(response).to redirect_to(opcion_cas_url)
    end
  end
end
