require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/personas_areas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PersonasArea. As you add validations to PersonasArea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PersonasArea.create! valid_attributes
      get personas_areas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      personas_area = PersonasArea.create! valid_attributes
      get personas_area_url(personas_area)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_personas_area_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      personas_area = PersonasArea.create! valid_attributes
      get edit_personas_area_url(personas_area)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PersonasArea" do
        expect {
          post personas_areas_url, params: { personas_area: valid_attributes }
        }.to change(PersonasArea, :count).by(1)
      end

      it "redirects to the created personas_area" do
        post personas_areas_url, params: { personas_area: valid_attributes }
        expect(response).to redirect_to(personas_area_url(PersonasArea.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PersonasArea" do
        expect {
          post personas_areas_url, params: { personas_area: invalid_attributes }
        }.to change(PersonasArea, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post personas_areas_url, params: { personas_area: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested personas_area" do
        personas_area = PersonasArea.create! valid_attributes
        patch personas_area_url(personas_area), params: { personas_area: new_attributes }
        personas_area.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the personas_area" do
        personas_area = PersonasArea.create! valid_attributes
        patch personas_area_url(personas_area), params: { personas_area: new_attributes }
        personas_area.reload
        expect(response).to redirect_to(personas_area_url(personas_area))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        personas_area = PersonasArea.create! valid_attributes
        patch personas_area_url(personas_area), params: { personas_area: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested personas_area" do
      personas_area = PersonasArea.create! valid_attributes
      expect {
        delete personas_area_url(personas_area)
      }.to change(PersonasArea, :count).by(-1)
    end

    it "redirects to the personas_areas list" do
      personas_area = PersonasArea.create! valid_attributes
      delete personas_area_url(personas_area)
      expect(response).to redirect_to(personas_areas_url)
    end
  end
end
